import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const segoeUI = localFont({
  src: "../assets/fonts/SegoeUI.ttf",
});

const BlueParadise = localFont({
  src: "../assets/fonts/BlueParadise.otf",
  variable: "--font-BlueParadise",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${segoeUI.className} ${BlueParadise.variable}`}>
        {children}
      </body>
    </html>
  );
}
