name: Auto Translate to English

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - "content/pt/**/*.mdx"

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci || npm install

      - name: Get modified and deleted files
        id: changed
        run: |
          modified_files=$(git diff --name-only --diff-filter=AM HEAD^ HEAD | grep '^content/pt/' || true)
          deleted_files=$(git diff --name-only --diff-filter=D HEAD^ HEAD | grep '^content/pt/' || true)

          {
            echo "modified_files<<EOF"
            echo "$modified_files"
            echo "EOF"
            echo "deleted_files<<EOF"
            echo "$deleted_files"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Process translations and deletions
        if: "!contains(github.event.head_commit.message, 'auto-translate')"
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          echo "Modified files received: ${{ steps.changed.outputs.modified_files }}"
          echo "Deleted files received: ${{ steps.changed.outputs.deleted_files }}"

          for file in ${{ steps.changed.outputs.modified_files }}; do
            if [ -f "$file" ]; then
              echo "Translating: $file"
              npx tsx src/scripts/translate.ts "$file"
            fi
          done

          for file in ${{ steps.changed.outputs.deleted_files }}; do
            relative_path=${file#content/pt/}
            en_file="content/en/$relative_path"
            if [ -f "$en_file" ]; then
              echo "Deleting: $en_file"
              rm "$en_file"
              git add "$en_file"
            fi
          done

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add content/en

          if git diff --cached --quiet; then
            echo "No translations or deletions to commit."
          else
            git commit -m "feat (auto-translate): sync updated and deleted files"
            git push
          fi
